/* eslint-disable global-require */
module.exports = {
  User: require('./User'),
  Admin: require('./Admin'),
  Role: require('./Role'),
  Permission: require('./Permission'),
  Category: require('./Category'),
  SubCategory: require('./SubCategory'),
  Brand: require('./Brand'),
  Attribute: require('./Attribute'),
  Product: require('./Product'),
  ProductVariant: require('./ProductVariant'),
  Inventory: require('./Inventory'),
  Cart: require('./Cart'),
  Wishlist: require('./Wishlist'),
  Address: require('./Address'),
  Order: require('./Order'),
  OrderItem: require('./OrderItem'),
  Payment: require('./Payment'),
  Coupon: require('./Coupon'),
  CouponUsage: require('./CouponUsage'),
  Review: require('./Review'),
  Banner: require('./Banner'),
  Blog: require('./Blog'),
  BlogCategory: require('./BlogCategory'),
  FAQ: require('./FAQ'),
  Page: require('./Page'),
  Newsletter: require('./Newsletter'),
  EmailOTP: require('./EmailOTP'),
  Notification: require('./Notification'),
  ContactMessage: require('./ContactMessage'),
  Setting: require('./Setting'),
  Counter: require('./Counter'),
  SearchTerm: require('./SearchTerm'),
};
